{% set name = "mythx-models" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mythx-models-{{ version }}.tar.gz
  sha256: e6494e669e67346d8b3a206ce861890c7c95f3670b69217028edd0ff3401267a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<4
  run:
    - inflection ==0.5.1
    - jsonschema ==3.2.0
    - pydantic ==1.7.3
    - python >=3.6,<4
    - python-dateutil ==2.8.1

test:
  imports:
    - mythx_models
    - mythx_models.request
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmuhs/mythx-models
  summary: Python domain model classes for the MythX platform
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
